- image_explorer/image_explorer.py
- image_explorer/templates/html/image_explorer_edit.html
- image_explorer/translations/en/LC_MESSAGES/text.po
- image_explorer/translations/eo/LC_MESSAGES/text.po
- setup.py
[WL-367](https://openedx.atlassian.net/browse/WL-367)
@mattdrayer fyi, however I have asked a question on JIRA. I will perform an update if it is required as per my question. 
Thanks
> WL-367 18n support: Zooming Image Tool

- .tx/config
- README.md
- image_explorer/translations/ar/LC_MESSAGES/text.po
- image_explorer/translations/es_419/LC_MESSAGES/text.po
- image_explorer/translations/fr/LC_MESSAGES/text.po
- image_explorer/translations/he/LC_MESSAGES/text.po
- image_explorer/translations/hi/LC_MESSAGES/text.po
- image_explorer/translations/ko_KR/LC_MESSAGES/text.po
- image_explorer/translations/pt_BR/LC_MESSAGES/text.po
- setup.py
This PR added translation files download from transifex and transifex config to support WL-580.
@douglashall could you please review it?
> ziafazal/WL-580: added translation files and transifex config

- README.md
This PR adds documentation for student_view_data
> add documentation for student_view_data

- image_explorer/image_explorer.py
- image_explorer/public/css/image_explorer.css
- image_explorer/public/js/image_explorer.js
- image_explorer/templates/html/image_explorer.html
- jQuery fix to translate hotspot X & Y axis from pixel to %
- Fixed popup for mobile
@bradenmacdonald Please review this PR
> MCKIN-5629 Responsive hotspots and popups for mobile

- image_explorer/public/css/image_explorer.css
- Reduced hotspot size on mobile from 28px to 16px
@bradenmacdonald Please review this minor change from MCKIN-5629
> Reduced hotspot size on mobile

- image_explorer/image_explorer.py
- setup.py
- tests/unit/test_image_explorer.py
@murad-hubib has made Image Explorer responsive and is now mostly usable on mobile, this PR enables mobile views.
> MCKIN-5939: Enables mobile support

- image_explorer/image_explorer.py
- image_explorer/public/css/image_explorer.css
- image_explorer/public/js/image_explorer_edit.js
- image_explorer/templates/html/image_explorer.html
- image_explorer/templates/html/image_explorer_edit.html
- setup.py
- tests/unit/test_image_explorer.py
- Added feature flag for calculating hotspots in % (False by default to make it backward compatible)
- Added styles for studio
- Updated new version from 0.4.3 to 0.5.0
> Added feature flag for new hotspots calculation

- image_explorer/image_explorer.py
- setup.py
Replace static from background url with static_replace app from edx-platform.
**JIRA tickets:** MCKIN-7042
**Dependencies:**
edx-platform/common/djangoapps/static_replace
> Replace static from background url

- image_explorer/public/css/image_explorer.css
- setup.py
Changes include fixing hotspot feedback design in studio
> YONK-950: Hotspots feedback is showing properly on Studio

- image_explorer/public/css/image_explorer.css
- setup.py
Reverts edx-solutions/xblock-image-explorer#40
> Revert "YONK-950: Hotspots feedback is showing properly on Studio"

- image_explorer/image_explorer.py
- image_explorer/public/css/image_explorer.css
- image_explorer/public/js/image_explorer.js
- image_explorer/templates/html/image_explorer.html
- Added hotspot detail pane for image explorer V2
@kaizoku Please review and merge 
**Steps to check:**
- Just click  any hotspot and the details of the hotspot should appear in the pane on right side.
Ticket: [https://edx-wiki.atlassian.net/browse/MCKIN-7571](https://edx-wiki.atlassian.net/browse/MCKIN-7571)
CC: @bradenmacdonald  @xitij2000
> MCKIN-7571 IE V2 hotspot detail pane

- image_explorer/public/js/image_explorer.js
- setup.py
It just adds a class 'visited' once user has clicked the popup opener button so that we can customize the user experience once they have visited it.
> To differentiate popups that has  been visited/clicked by a user.

- .circleci/config.yml
- .python-version
- README.md
- image_explorer/__init__.py
- image_explorer/image_explorer.py
- image_explorer/utils.py
- pylintrc
- tox.ini
This improves the code quality of this xblock and doesn't change it's functionality.
**Reviewers: **
> BB-1203: Improve xblock-image-explorer code quality

- image_explorer/templates/html/image_explorer.html
- setup.py
aria-label provided for IE hotspot.
> MCKIN-12283 aria-label provided on IE hotspot

- image_explorer/image_explorer.py
- image_explorer/public/css/image_explorer.css
- image_explorer/public/js/image_explorer.js
- image_explorer/templates/html/image_explorer.html
- setup.py
- tests/integration/test_image_explorer.py
This PR removes popup html out of hotspot button to make it valid html and fixes a11y issues.
> MCKIN-12182: a11y: Ensure dialogs use proper structure

- image_explorer/templates/html/image_explorer.html
- setup.py
> Adds playsinline for BC videos

- image_explorer/public/css/image_explorer.css
- image_explorer/templates/html/image_explorer.html
- setup.py
Make the Cross Icon visible and adjust its sequence as accessibility concern.
> MCKIN-12927 | make the Cross Icon visible and adjust its sequence as accessibility concern.

- image_explorer/templates/html/image_explorer.html
- setup.py
IE SR reading loop issue resolved
> MCKIN-13073 IE SR reading loop issue resolved

- image_explorer/public/js/image_explorer.js
- setup.py
Focus order fixed for IE and Edge
> MCKIN-13194 Focus order fixed for IE and Edge

- image_explorer/templates/html/image_explorer.html
IE fix for Chrome and Internet explorer
> MCKIN-13279 IE fix for Chrome and Internet explorer

- image_explorer/templates/html/image_explorer.html
- setup.py
Dialog content made reader accessible
> MCKIN-13279 Dialog content made reader accessible

- .tx/config
- Updating `Transifex` client config for new `Transifex` client.
> chore: update transifex config for new transifex client
